Hi, I'm going to apply 2 supervised machine learning classification models on the given dataset to classify mushrooms as poisonous or eatable

1. Logistic Regression Model
2. KNN (K- Nearest Neighbours)

I'll proceed by converting categorical variables into dummy/indicator variables and scaling the dataset. I'll test the dataset on both the algorithms.

    Importing important Libraries

In [1]:
import numpy as np
import pandas as pd

Importing Data

In [2]:
dataset = pd.read_csv('../input/mushroom-classification/mushrooms.csv')

Printing the first 5 rows from the dataset to see the data

In [3]:
dataset.head(5)

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

Checking whether there is null value in any of the columns

In [4]:
dataset.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

Printing the names of the columns of the dataset

In [5]:
dataset.columns

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

Converting the categorical columns

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in dataset.columns:
    dataset[col] = le.fit_transform(dataset[col])

In [7]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(), [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22])],
remainder='passthrough'                         
)

Scaling Dataset

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(dataset)
X_test = sc.transform(dataset)

finding the correlation between the metrics with respect to column "class"

In [9]:
Corr= dataset.corr()['class'].sort_values()
Corr

gill-color                 -0.530566
bruises                    -0.501530
ring-type                  -0.411771
stalk-root                 -0.379361
gill-spacing               -0.348387
stalk-surface-above-ring   -0.334593
stalk-surface-below-ring   -0.298801
ring-number                -0.214366
stalk-color-above-ring     -0.154003
stalk-color-below-ring     -0.146730
stalk-shape                -0.102019
odor                       -0.093552
cap-color                  -0.031384
cap-shape                   0.052951
gill-attachment             0.129200
veil-color                  0.145142
spore-print-color           0.171961
cap-surface                 0.178446
habitat                     0.217179
population                  0.298686
gill-size                   0.540024
class                       1.000000
veil-type                        NaN
Name: class, dtype: float64

Separating the independent variables (X) and the dependent variables (y)

In [10]:
X= dataset.iloc[:,1:22].values
y=dataset.iloc[:,0].values

Deleting the column "veil-type"

In [11]:
np.delete(X,16,axis=1)

array([[5, 2, 4, ..., 4, 2, 3],
       [5, 2, 9, ..., 4, 3, 2],
       [0, 2, 8, ..., 4, 3, 2],
       ...,
       [2, 2, 4, ..., 4, 0, 1],
       [3, 3, 4, ..., 0, 7, 4],
       [5, 2, 4, ..., 4, 4, 1]])

Splitting dataset into Test data and Training Data

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 1234)

Checking the length of test and training data

In [13]:
print(len(X_train), len(X_test), len(y_train), len(y_test))

6499 1625 6499 1625


# Logistic Regression

In [14]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()
log_reg.fit(X_train,y_train)

/opt/conda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
y_pred = log_reg.predict(X_train)

The score of training dataset

In [16]:
log_reg.score(X_train, y_train)

0.9484536082474226

To check the score of test data

In [17]:
log_reg.score(X_test,y_test)

0.9476923076923077

Applying Confusion matrix

In [18]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_train, y_pred)
cm

array([[3253,  138],
       [ 197, 2911]])

In [19]:
from sklearn.metrics import precision_score, recall_score, f1_score
precision_score(y_train, y_pred)
recall_score(y_train, y_pred)
f1_score(y_train, y_pred)

0.9455903849277245

# KNN(K- nearest Neighbours)

In [20]:
from sklearn.neighbors import KNeighborsClassifier
#knn = KNeighborsClassifier(n_neighbors = 15)
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

Checking the scores of train data after applying KNN

In [21]:
knn.score(X_train,y_train)

0.9993845206954917

Checking the scores of test data after applying KNN

In [22]:
knn.score(X_test,y_test)

0.9969230769230769

In [23]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_train,y_pred)
cm

array([[3253,  138],
       [ 197, 2911]])

In [24]:
from sklearn.metrics import precision_score,recall_score,f1_score
precision_score(y_train,y_pred)

0.9547392587733683

In [25]:
recall_score(y_train,y_pred)

0.9366151866151866

In [26]:
f1_score(y_train,y_pred)

0.9455903849277245